repos:
    - repo: local
      hooks:
          - id: line-length
            name: Enforce 99-char line length
            entry: python scripts/check_line_length.py
            language: system
            pass_filenames: false
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.6.9
      hooks:
          - id: ruff
            args: [--line-length=99]
          - id: ruff-format
