# Story flag constants for Act II: Greendale & The Forest Edge

# Main Quest Progression Flags
FLAG_ARRIVED_IN_GREENDALE = "arrived_in_greendale"
FLAG_SPOKEN_TO_SIR_CEDRIC = "spoken_to_sir_cedric"
FLAG_GATHERING_STORM_ACCEPTED = "gathering_storm_accepted"
FLAG_GATHERING_STORM_COMPLETED = "gathering_storm_completed"

# Greendale Phase Quest Flags
FLAG_KNIGHTS_TEST_ACCEPTED = "knights_test_accepted"
FLAG_KNIGHTS_TEST_COMPLETED = "knights_test_completed"
FLAG_DEMONSTRATED_COMBAT_SKILLS = "demonstrated_combat_skills"
FLAG_SUPPLIES_QUEST_ACCEPTED = "supplies_quest_accepted"
FLAG_SUPPLIES_QUEST_COMPLETED = "supplies_quest_completed"
FLAG_ECHOES_OF_PAST_ACCEPTED = "echoes_of_past_accepted"
FLAG_ECHOES_OF_PAST_COMPLETED = "echoes_of_past_completed"
FLAG_HEALERS_APPRENTICE_ACCEPTED = "healers_apprentice_accepted"
FLAG_HEALERS_APPRENTICE_COMPLETED = "healers_apprentice_completed"
FLAG_CEDRIKS_HONOR_ACCEPTED = "cedriks_honor_accepted"
FLAG_CEDRIKS_HONOR_COMPLETED = "cedriks_honor_completed"
FLAG_INNKEEPERS_DAUGHTER_ACCEPTED = "innkeepers_daughter_accepted"
FLAG_INNKEEPERS_DAUGHTER_COMPLETED = "innkeepers_daughter_completed"
FLAG_ANCIENT_LIBRARY_ACCEPTED = "ancient_library_accepted"
FLAG_ANCIENT_LIBRARY_COMPLETED = "ancient_library_completed"

# Forest Phase Quest Flags
FLAG_HERMITS_WARNING_ACCEPTED = "hermits_warning_accepted"
FLAG_HERMITS_WARNING_COMPLETED = "hermits_warning_completed"
FLAG_FOREST_RIDDLES_ACCEPTED = "forest_riddles_accepted"
FLAG_FOREST_RIDDLES_COMPLETED = "forest_riddles_completed"
FLAG_WHISPERS_IN_WIND_ACCEPTED = "whispers_in_wind_accepted"
FLAG_WHISPERS_IN_WIND_COMPLETED = "whispers_in_wind_completed"
FLAG_LOST_CARAVAN_ACCEPTED = "lost_caravan_accepted"
FLAG_LOST_CARAVAN_COMPLETED = "lost_caravan_completed"

# Character Relationship Flags
FLAG_CEDRIC_TRUSTS_ELIOR = "cedric_trusts_elior"
FLAG_CEDRIC_TRUST_LEVEL_1 = "cedric_trust_level_1"
FLAG_CEDRIC_TRUST_LEVEL_2 = "cedric_trust_level_2"
FLAG_CEDRIC_TRUST_LEVEL_3 = "cedric_trust_level_3"
FLAG_LYRIA_RELATIONSHIP_STUDENT = "lyria_relationship_student"
FLAG_LYRIA_RELATIONSHIP_COLLEAGUE = "lyria_relationship_colleague"
FLAG_NYX_FIRST_MEETING = "nyx_first_meeting"
FLAG_NYX_TRIALS_COMPLETED = "nyx_trials_completed"
FLAG_ELENA_CURSE_BROKEN = "elena_curse_broken"
FLAG_KNOWS_ELENA_CURSE = "knows_elena_curse"
FLAG_MARCUS_GRATEFUL = "marcus_grateful"
FLAG_SPECTRAL_LIBRARIAN_FRIENDLY = "spectral_librarian_friendly"

# Learning and Interaction Flags
FLAG_LEARNED_MEND_FROM_CRAFTSMEN = "learned_mend_from_craftsmen"
FLAG_SHOWED_JOURNAL_TO_HISTORIANS = "showed_journal_to_historians"
FLAG_READ_TRAVELERS_JOURNAL = "read_travelers_journal"
FLAG_GAVE_MERCHANTS_FLYER = "gave_merchants_flyer"
FLAG_PREMIUM_SELECTION_AVAILABLE = "premium_selection_available"
FLAG_SPOKEN_TO_CARAVAN_MASTER = "spoken_to_caravan_master"
FLAG_COURT_HERALD_FORMAL_PRESENTATION = "court_herald_formal_presentation"
FLAG_RESEARCHED_FAMILY_HERITAGE = "researched_family_heritage"
FLAG_HELPED_ELDERLY_RESIDENTS = "helped_elderly_residents"
FLAG_ACCESSED_INN_ROOM = "accessed_inn_room"
FLAG_USED_CITY_MAP = "used_city_map"
FLAG_FOUND_LOST_CARAVAN = "found_lost_caravan"
FLAG_HEALERS_APPRENTICE_READY = "healers_apprentice_ready"
FLAG_PROTECTIVE_CHARM_USED_FOREST_ENTRANCE = "protective_charm_used_forest_entrance"
FLAG_FOREST_TRANSITION_KIT_USED = "forest_transition_kit_used"
FLAG_FOREST_MAP_USED_FOREST_ENTRANCE = "forest_map_used_forest_entrance"
FLAG_ENHANCED_LANTERN_USED_FOREST_ENTRANCE = "enhanced_lantern_used_forest_entrance"
FLAG_FOREST_GUARDIANS_RIDDLES_OFFERED = "forest_guardians_riddles_offered"
FLAG_FOREST_GUARDIANS_RIDDLES_COMPLETED = "forest_guardians_riddles_completed"
FLAG_WATER_NYMPH_RIDDLES_COMPLETED = "water_nymph_riddles_completed"
FLAG_WHISPERS_IN_WIND_OFFERED = "whispers_in_wind_offered"
FLAG_GAVE_ACORN_TO_TREE_SPIRIT = "gave_acorn_to_tree_spirit"
FLAG_LEARNED_FOREST_SPEECH = "learned_forest_speech"
FLAG_ENCHANTED_ACORN_TAKEN = "enchanted_acorn_taken"
FLAG_SILVER_LEAVES_TAKEN = "silver_leaves_taken"
FLAG_DRUIDIC_FOCUS_TAKEN = "druidic_focus_taken"
FLAG_CRYSTAL_CLEAR_WATER_TAKEN = "crystal_clear_water_taken"
FLAG_MOONFLOWERS_TAKEN = "moonflowers_taken"
FLAG_STANDING_STONES_EXAMINED = "standing_stones_examined"
FLAG_NATURE_SENSE_LEARNED = "nature_sense_learned"
FLAG_NATURE_SENSE_USED_WHISPERING_GLADE = "nature_sense_used_whispering_glade"
FLAG_SILVER_TREE_EXAMINED = "silver_tree_examined"
FLAG_MENDED_LIBRARY_ENCHANTMENTS = "mended_library_enchantments"

# Spell Learning Flags
# FLAG_LEARNED_MEND = "learned_mend"
# FLAG_LEARNED_GREATER_HEAL = "learned_greater_heal"
# FLAG_LEARNED_DISPEL = "learned_dispel"
# FLAG_LEARNED_NATURE_SENSE = "learned_nature_sense"
# FLAG_LEARNED_FOREST_SPEECH = "learned_forest_speech"
# FLAG_LEARNED_PROPHETIC_VISION = "learned_prophetic_vision"

# Location Access Flags
# FLAG_GREENDALE_GATES_ACCESSED = "greendale_gates_accessed"
# FLAG_CASTLE_ACCESS_GRANTED = "castle_access_granted"
# FLAG_HIDDEN_LIBRARY_DISCOVERED = "hidden_library_discovered"
# FLAG_FOREST_ENTRANCE_UNLOCKED = "forest_entrance_unlocked"
# FLAG_ANCIENT_GROVE_ACCESSED = "ancient_grove_accessed"
# FLAG_HEART_OF_FOREST_REACHED = "heart_of_forest_reached"

# Important Item Flags
# FLAG_HAS_CITY_MAP = "has_city_map"
# FLAG_HAS_ENTRY_PASS = "has_entry_pass"
# FLAG_HAS_SURVIVAL_KIT = "has_survival_kit"
# FLAG_HAS_FOREST_GUIDE = "has_forest_guide"
# FLAG_HAS_PROTECTIVE_CHARM = "has_protective_charm"
# FLAG_HAS_HEALING_POTION = "has_healing_potion"
# FLAG_HAS_CRYSTAL_FOCUS = "has_crystal_focus"
# FLAG_HAS_NYX_TOKEN = "has_nyx_token"
# FLAG_HAS_FOREST_HEART_CRYSTAL = "has_forest_heart_crystal"

# World State Flags
# FLAG_GREENDALE_PHASE_COMPLETE = "greendale_phase_complete"
# FLAG_FOREST_PHASE_COMPLETE = "forest_phase_complete"
# FLAG_ALL_SIDE_QUESTS_COMPLETE = "all_side_quests_complete"
# FLAG_READY_FOR_NYX_TRIALS = "ready_for_nyx_trials"
# FLAG_PROPHETIC_VISIONS_UNLOCKED = "prophetic_visions_unlocked"

# Optional Content Flags
# FLAG_EXPLORED_HIDDEN_AREAS = "explored_hidden_areas"
# FLAG_DEEP_LORE_DISCOVERED = "deep_lore_discovered"
# FLAG_ENVIRONMENTAL_CHAMPION = "environmental_champion"
# FLAG_CITY_CITIZENSHIP_EARNED = "city_citizenship_earned"
